# 服务器配置
server:
  port: 3000

spring:
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
      
  # MySQL数据库配置
  datasource:
    
    
    # HikariCP 连接池配置
    hikari:
      connection-timeout: 20000    # 数据库连接超时时间(毫秒)
      maximum-pool-size: 100       # 最大数据库连接数
      minimum-idle: 20             # 数据库连接池保持数据连接的最小数量
      idle-timeout: 300000          # 空闲连接最长保持时间(毫秒)
      max-lifetime: 18000000        # 连接最大生命周期(毫秒)
  
  # 文件上传配置
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  
  # JPA配置
  jpa:
    open-in-view: false
  
  # Thymeleaf配置
  thymeleaf:
    check-template-location: false

# Swagger配置
swagger:
  enabled: true

file:
  #upload-dir: /root/picture
  upload-dir: C:/Users/hideon27/IdeaProjects/handle/src/main/resources/pictures
  #upload-dir:C:/Users/hideon27/Desktop/pictures



