# 服务器配置
server:
  port: 3000

spring:
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
      
  # MySQL数据库配置
  datasource:
    
    
    # HikariCP 连接池配置
    hikari:
      connection-timeout: 20000    # 数据库连接超时时间(毫秒)
      maximum-pool-size: 100       # 最大数据库连接数
      minimum-idle: 20             # 数据库连接池保持数据连接的最小数量
      idle-timeout: 300000          # 空闲连接最长保持时间(毫秒)
      max-lifetime: 18000000        # 连接最大生命周期(毫秒)
  
  # 文件上传配置
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  
  # JPA配置
  jpa:
    open-in-view: false
  
  # Thymeleaf配置
  thymeleaf:
    check-template-location: false

file:
  #upload-dir: /root/picture
  upload-dir: C:/Users/hideon27/IdeaProjects/handle-service/src/main/resources/pictures
  #upload-dir:C:/Users/hideon27/Desktop/pictures

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    enabled: true
    path: /v3/api-docs

knife4j:
  enable: true
  setting:
    language: zh-CN
    enableSwaggerModels: true
    enableDocumentManage: true
    swaggerModelName: 实体类列表
    enableVersion: false
    enableReloadCacheParameter: false
    enableAfterScript: true
    enableFilterMultipartApiMethodType: POST
    enableFilterMultipartApis: false
    enableRequestCache: true
    enableHost: false
    enableHostText: ""
    enableHomeCustom: false
    enableSearch: true
    enableFooter: false
    enableFooterCustom: true
    footerCustomContent: Apache License 2.0 | Copyright  2024-[岩芯图像管理系统]



